### ISSUE TITLE
'set -e' in bootbind stops it from reporting failure to find current ESP

### ISSUE THREAD

**Issue by kpfleming** [gregory-lee-bartholomew/bootsync#3]
https://github.com/gregory-lee-bartholomew/bootsync/blob/cd2ea0040a345fcdb9d0b0059521bf045d9fe82f/bootbind#L4

If the `grep` commands in lines 31 or 37 fail to find a string which matches the pattern, they'll exit with a non-zero code instead of silently failing; with `set -e` in place this causes bash to stop execution and thus the intended error message is never emitted.

I don't think there's a way to get `grep` to just output nothing with a zero code in the case of a match failure, so it's probably best to remove (or comment) out the `set -e` line.

**Comment by gregory-lee-bartholomew** [comment]
I completely agree that `set -e` is pretty useless the way the rest of this script is written. Thanks again for your help!

BTW, it's not actually the `grep` that is causing the pipeline to fail. It is the `read` at the end. Below are the relevant excerpts from the Bash man page.

> **set -e**:
> The shell does not exit if  the  command that fails is ... any command in a pipeline but the last ...

> **read**:
> The exit status is zero, unless end-of-file is encountered ...

Without `set -e`, I can also remove some `|| true` statements at the end. ... But on second thought, I think I'll remove those commands completely and let the script error out normally if the mount fails for whatever reason. `/boot` should have been created during the installation phase. This script shouldn't try to correct that at runtime.
